# Generated by Django 5.1.1 on 2024-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('LS', 'Lifestyle'), ('TC', 'Technology'), ('TR', 'Travel'), ('BN', 'Business'), ('EC', 'Economy'), ('SP', 'Sports')], max_length=255),
        ),
    ]
