# Generated by Django 5.1.1 on 2024-10-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='category',
            field=models.TextField(choices=[('LS', 'Lifestyle'), ('TC', 'Technology'), ('TR', 'Travel'), ('BN', 'Business'), ('EC', 'Economy'), ('SP', 'Sports')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
