# Generated by Django 5.1.1 on 2024-10-03 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogdetails_category_delete_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDetails',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'BLogs'},
        ),
    ]
