# Generated by Django 5.1.1 on 2024-10-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_blogdetails_blog_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blogs'},
        ),
    ]
