# Generated by Django 5.1.1 on 2024-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_alter_blog_options_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
