# Generated by Django 5.1.1 on 2024-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default='James', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='l_name',
            field=models.CharField(default='Joe', max_length=10),
        ),
    ]
