# Generated by Django 5.1.1 on 2024-10-10 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_options_alter_profile_f_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acc_created',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
