# Generated by Django 5.1.1 on 2024-10-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_acc_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
