# Generated by Django 5.1.1 on 2024-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_acc_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(default='_job', max_length=10),
        ),
    ]
