# Generated by Django 5.1.1 on 2024-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='img/dp.jpg', upload_to='dp_img/'),
        ),
    ]
