# Generated by Django 5.1.1 on 2024-10-12 14:10

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default=authentication.models.get_default_image_path, upload_to='dp_img/'),
        ),
    ]
